---
engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "lib/**"
  - "**.rb"
  - "*.md"
  - "Rakefile"
exclude_paths:
- "Gemfile"
- "*.gemspec"
